language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install pymunk --use-mirrors"
  - "pip install Pygame --use-mirrors"
# command to run tests
script: python -m unittest discover
