language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - xvfb
before_install:
  - "sudo apt-get install freeglut3-dev"
install:
  - "pip install pymunk==4"
  - "pip install pyglet"
  - "pip install --upgrade https://github.com/jorgecarleitao/pyglet-gui/archive/master.zip"
script: 
  - "python -m unittest discover"
notifications:
  email:
    on_success: change
    on_failure: change
