language: python
python:
  - "3.2"
  - "3.3"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install pymunk --use-mirrors"
  - "pip install --upgrade http://pyglet.googlecode.com/archive/tip.zip"
  - "pip install --upgrade https://github.com/jorgecarleitao/pyglet-gui/archive/master.zip"
script: 
  - "python -m unittest discover"
notifications:
  email:
    on_success: change
    on_failure: change
